### ISSUE TITLE
TransformValue and TransformComponent asMatrix methods should return DOMMatrix.

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#103]

**Comment by heycam** [comment]
Note that I think we still need `Matrix`, as we want an object that represents a single **matrix(...)** value in a transform list.  But also I don't think we want `matrix` to duplicate (and be different from) `DOMMatrix`'s interface.  For example `DOMMatrix` uses `m11`, `m12`, etc. for 3D components rather than `a`, `b`, ...

Should `Matrix` be something like:

```
interface Matrix : TransformComponent {
  DOMMatrixReadOnly matrix;
};
````

and if so, should we keep a constructor on `Matrix` and make it have the same arguments as [`DOMMatrix`'s constructor arguments](https://drafts.fxtf.org/geometry/#DOMMatrix)?

**Comment by shans** [comment]
I would be quite happy for Matrix to only have a constructor that takes a
DOMMatrix. It would be easy to add extra constructors later if we felt the
need.

**Comment by shans** [comment]
Oh, this is done.
