### ISSUE TITLE
[css-typed-om] Color models and color spaces are mixed in CSSColorValue

### ISSUE THREAD

**Issue by carlosame** [w3c/css-houdini-drafts#1044]
CSSColorValue has a [colorSpace](https://drafts.css-houdini.org/css-typed-om-1/#dom-csscolorvalue-colorspace) attribute that can have values like "rgb", "hsl", "hwb" or "device-cmyk". However, those aren't exactly color spaces but color models instead.

Reading other issues, it seems that "rgb" implies sRGB but I find it a bit confusing, and then one has `to("srgb")` and `to("rgb")` returning different objects as mentioned here: https://github.com/w3c/css-houdini-drafts/issues/1036#issuecomment-840650632.

I suggest having both `colorSpace` and `colorModel`, with `colorModel` having the same kind of values as the current `colorSpace`, and the new `colorSpace` containing the actual color space (sRGB, p3, ...).

**Comment by svgeesus** [comment]
I agree that it is confusing. In general "RGB" should be taken to mean an overall color model, in some unspecified colorspace.

However these names come from the CSS syntax, and have existed since CSS1; and in that specific usage, the `rgb()` function does not mean "some random RGB colorspace" but means "[a color in the sRGB colorspace](https://drafts.csswg.org/css-color-4/#numeric-srgb)". Similarly, in CSS syntax, both `hsl()` and `hwb()` [refer to a color in the sRGB colorspace](https://drafts.csswg.org/css-color-4/#the-hsl-notation):

> HSL colors resolve to sRGB.
> HWB colors resolve to sRGB

For `device-cmyk` you are quite correct; this is really a color model and, although [we try to provide a colorimetric interpretation](https://drafts.csswg.org/css-color-4/#device-cmyk) this is not always possible. (Note that [calibrated CMYK color spaces are also supported in CSS](https://drafts.csswg.org/css-color-4/#cal-cmyk), via [the `color()` function](https://drafts.csswg.org/css-color-4/#color-function) together with the [`@color-profile` rule](https://drafts.csswg.org/css-color-4/#at-profile)).

The basic problem is that the CSS Typed OM, like the CSS OM, is tightly coupled to the CSS syntax and is primarily concerned with reflecting back to script exactly what CSS syntax was originally used to define the color. It is not a general Color object model for the Web platform. Therefore, the terminology has to be understood within the specific, largely historical, confines of CSS syntactic forms

**Comment by carlosame** [comment]
> For `device-cmyk` you are quite correct; this is really a color model and, although we try to provide a colorimetric interpretation this is not always possible.

`device-cmyk` could have a `colorModel` of `CMYK` and a `colorSpace` of `device-cmyk`.

> It is not a general Color object model for the Web platform. Therefore, the terminology has to be understood within the specific, largely historical, confines of CSS syntactic forms

If one writes a script today, and then another predefined color space is added to the `color()` function and is used, that script would no longer know which color model is being used. Same thing for custom-profiled colors: I do not know the color model because the Typed OM does not give me that information. Knowing the color model is essential for basic use cases.

To be more specific, my suggestion would be to use the values in the "Signature" column of Table 19 in the ICCv4 specification as the possible values for `colorModel`, plus `HSL` and `HWB`. And `colorSpace` could be left as it is now (so the current mapping to syntactic forms is respected).

**Comment by tabatkins** [comment]
As Chris said, the Typed OM is intended to represent CSS values in the form of JS objects; any use beyond that is incidental. In particular, CSSColorValue and its subclasses are *not* intended to be an accurate, general-purpose color representation or manipulation library.

The current design is driven by a few considerations:

1. For `CSSColor` values (representing the CSS `color()` function), I need to expose the color space keyword given as the first argument (currently, one of the [`<predefined-rgb>`](https://drafts.csswg.org/css-color-4/#typedef-predefined-rgb) or [`<xyz-space>`](https://drafts.csswg.org/css-color-4/#typedef-xyz-space) keywords).
2. For the `CSSColorValue.to()` method, which allows you to convert a value between the various CSS functions, I need a way to identify the function you want to convert to (or, for `color()`, which color space you want to convert to). For `color()` I can obviously just use the color space keyword; for the other CSS color functions the most obvious choice is to use the function name.
3. Since the `.colorSpace` and `.to()` values match for `CSSColor`, it seems reasonable to shift `.colorSpace` up to the superclass and have it match for *all* the subclasses, so `CSSRGB` (representing the CSS `rgb()` function) has "rgb" for both, etc.

I believe the current design gives the most straightforward and understandable result for manipulating CSS values, even if it's odd, incomplete, or inaccurate when discussing colors more generally. I don't believe it's valuable *for the Typed OM* to try and be more accurate in general color terminology; that's simply not what it's meant for. @svgeesus and @LeaVerou are working on a `Color` class for the web platform that *does* accurately reflect colors and is *not* deeply tied to CSS syntax.
