### ISSUE TITLE
[css-properties-and-values-api] define how typed custom properties influence @supports

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#118]
We should define how registered custom properties affect @supports.  For example if registered with type `<length>` then `@supports (--something: red)` would evaluate to false and `@supports (--something: 2px)` true.

**Comment by shans** [comment]
I'm leaning towards @supports behaving as in variables-1. @supports is supposed to be used for browser feature detection and it seems like a violation of this idea to allow JS library behavior to modify the result.

Added an issue to the spec so we can track and discuss.

**Comment by shans** [comment]
Tab has a counterpoint:

div {
  --foo: 3em;
  --foo: 5newlengthunits;
}

If --foo is registered as a length, then the second declaration will be discarded. @supports should behave the same.

**Comment by FremyCompany** [comment]
I agree, (a)supports should respect defined value types.

**Comment by heycam** [comment]
One thing to be mindful of is that this would be the first `@supports` expression that depends on state inside the document, and which needs to be dynamically evaluated. If custom property registrations change, the `@supports` rules need to be re-evaluated.

**Comment by shans** [comment]
Let's add a feature to `@supports` that allows us to test if a value is a member of a particular type. Then variables can always behave the same (regardless of what they're registered as) and you can use this new feature to solve Tab's problem.

**Comment by shans** [comment]
Let's just put a note in properties & values and define the behavior in `@supports`.

**Comment by jyc** [comment]
Would this be a little unintuitive? We would have "`(property: value)` implies that `property: value` is a valid declaration" for all standard properties, but `(--custom-property: value)` would mean something different (e.g. `@supports (--custom-property: invalid-value) { --custom-property: invalid-value }` would act strangely).

**Comment by tabatkins** [comment]
Added, with an explanatory note. This is actually consistent with our parsing behavior; registered custom properties still *accept* all valid token streams at parse time, same as unregistered ones, but if you violate the registered grammar it automatically becomes invalid at computed-value time. Since @supports tests parsing behavior, it thus should accept anything for a registered custom property regardless of registered grammar.


Note that:

> Tab has a counterpoint:

My counterpoint was wrong. In that example, the declaration using a bad unit is still the one that'll get chosen at parse time, discarding the previous one. It'll just then become invalid at computed-value time.

Plus, as argued elsewhere, the *use-case* for @supports with a registered custom property is essentially nil.  We need @supports because you're sending stylesheets to a panoply of browser versions, and you don't know what set of features will be valid on any individual one.  But with registered custom properties, you *know* what the feature set is; it's whatever is supported by the library you're currently using. This doesn't change across browser versions; it's completely under the author's control.

**Comment by heycam** [comment]
Thanks, that works for me.
