### ISSUE TITLE
[isolated-workers] Add console API to IsolatedWorkerGlobalScope

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#15]
Currently missing from draft. All console APIs should be available.

**Comment by bfgeek** [comment]
Fun fact: WorkerConsole or similar, isn't actually defined anywhere from what I can tell.
https://html.spec.whatwg.org/multipage/workers.html

Will wait patiently for a future where they are defined somewhere.

**Comment by domenic** [comment]
I have tried for a while to get people to spec console as an intro to standards. @terinjokes made some progress at https://github.com/terinjokes/console-spec. Recently I asked @robertkowalski to try picking up the banner. So: maybe soon?

**Comment by terinjokes** [comment]
:+1:

**Comment by robertkowalski** [comment]
Just a short update from me:

I tried to figure out how to make the console API testable by a "living documentation". It turns out that this part of the browsers is very hard to test. I was hoping that I could make a reference implementation that includes implementations and tests on the node.js platform but the idea did not get much love in the whatwg channel.

**Comment by terinjokes** [comment]
@robertkowalski mine repo has tests, but since the correct behavior of most of the console API is a side effect, it's very difficult to test in the normal way.

Do console messages get sent to selenium in any ways?

**Comment by robertkowalski** [comment]
great idea, yes that is indeed possible!

https://code.google.com/p/selenium/wiki/Logging

**Comment by domenic** [comment]
Honestly I think the tests are much less important than just writing the spec at this point.

**Comment by bfgeek** [comment]
Added in ee1b655b361db07fd2b1360425e52dec2284160f
\o/
