### ISSUE TITLE
[css-typed-om] getProperties should specify an order in which the properties is returned

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#178]

**Comment by shans** [comment]
Alphabetical for normal properties, code point order for custom properties, all custom properties after all normal properties.

This should be consistent with Web Animations too.

**Comment by shans** [comment]
Addressed by https://github.com/w3c/css-houdini-drafts/commit/35d46eac0f5ad22d6caebf892ec6b7458d493f51

**Comment by tabatkins** [comment]
Rewriting this now - removing getProperties() entirely (as a maplike, it already has a .keys() method), and it should return those keys in the order they're stored in the object, as that's significant.

However, the StylePropertyMap should dictate the order you describe for freshly-created maps that don't otherwise have an initial order specified.
