### ISSUE TITLE
[css-typed-om] CSSTokenStreamValue

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#221]
Stream seems too similar to https://streams.spec.whatwg.org/. Seems like the object represents a simple List... Any reason it can't just be an array?

**Comment by FremyCompany** [comment]
Thanks for your input! Renaming is already planned (see #193) and I'm therefore closing this issue on the behalf of the editors.

To answer your question, it cannot be an array because it might need to be subclassed later when TypedOM supports more ranges of values than the L1 spec does at this point.

**Comment by annevk** [comment]
Arrays can be subclassed...

**Comment by FremyCompany** [comment]
But they cannot subclass CSSValue, which any value would need to subclass ;-)

**Comment by shans** [comment]
This issue wasn't about the name, but about the representation. I'm re-opening this pending a decent resolution.

**Comment by tabatkins** [comment]
So it needs to remain a CSSValue, not an Array. Iterable is already there, so it's array-like, it just needs to define indexed getters, which are tracked in #239. Closing this issue.

**Comment by domenic** [comment]
Can someone state why it needs to subclass CSSValue?

**Comment by FremyCompany** [comment]
Sure, the reason is that the spec currently isn't complete. Level 1 will only support a subset of CSS Values.

As we add more and more values in subsequent levels, things will have to change from being CSSUnparsedValue to being CSSXyzabcValue. While we are doing so, we cannot break behaviors that expected the old shape. If the old shape is an Array, we would need to keep it an array, which would prevent us from returning an actual CSSValue, which would be really weird. Authors should be able to expect any css value to be an instanceof CSSValue, not just the Level 1 ones.

At least that is my understanding of it, anyone feel free to correct me.
