### ISSUE TITLE
import() setup is inefficient

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#229]
From @bzbarsky: "Every import() call is defined to do a separate fetch() per worklet. Every worklet creation is defined to do a separate fetch() per each resolved module URL. This means that with a service worker you can easily track worklet creation, not to mention being quite inefficient when worklets are created. There must be a better way to do this."

**Comment by bfgeek** [comment]
I think I set it up this way to make sure that "fetch a module script tree" had an appropriate settings object. But yeah didn't consider the service worker leaking of information.

We'll want to probably specify that all of the fetching (and import pre-processing, etc) occurs separately from the actual script creation (with the actual execution context).

@domenic does splitting up "fetch a module script tree" into; "fetch a module script tree resources" and "create a module script tree" or similar, make sense? If so I can start working on a PR for whatwg/html

**Comment by domenic** [comment]
Can you give me more background? In general within a single global, modules are never fetched more than once, due to the module map memoization. Keeping them as one algorithm helps enforce this memoization. What is Houdini doing that is different and needs an exception? You want to essentially break the module map <-> global correspondence, it sounds like?

**Comment by bfgeek** [comment]
Yeah that's right; as a `WorkletGlobalScope` can effectively be "cloned", i.e. the engine can create a new `WorkletGlobalScope` on demand, e.g. when spinning up a new paint thread for example.

So in the ideal world, we'd have a module-map* associated with the main `Worklet` object, which contains the url->source-mapping, and when we need to create a new `WorkletGlobalScope` post-task all of the required url->source-mapping over to a new thread to be created into actual scripts.

The bug is basically about establishing the invariant "within a single worklet object, modules are never fetched more than once" instead of "global scope object".

**Comment by bfgeek** [comment]
*not a true module-map as per the spec, just one that keep an url->source-code mapping.

**Comment by domenic** [comment]
So note how the module map <-> settings object association works. Each Document and WorkerGlobalScope *has* a module map. And each environment settings object has an *algorithM* for obtaining the module map. Then the environment settings object for windows looks up their associated Document's module map, and for WorkerGlobalScope just returns the WorkerGlobalScope's module map.

So how I would do this in spec land is to say that each Worklet *has* a module map, and have the algorithm for WorkletGlobalScope environment settings objects return the associated Worklet's module map. Then you can continue to use the existing fetch algorithms, but since they all consult the same module map, you'll get the memoization for free.

**Comment by bfgeek** [comment]
That makes sense, I'll probably need to add some fuzzy wording about thread-safe access to it, but I'll get you to review this one.

**Comment by bfgeek** [comment]
@domenic So just looking at a module map again, sharing of a module map doesn't seem allowed? As it stores a (`url` - `script`) pair, and the `script` always has an associated `realm` (and settings object).

One was to achieve the invariant is to hook the fetch algorithm, and have a cache on the `Worker` object....

**Comment by domenic** [comment]
Ah, hmm, I see. And yeah, that's an important intrinsic property, not just incidental. OK, so you need a module map per WorkletGlobalScope.

I think hooking the fetch algorithm makes some sense. I guess we'd add an additional hook in addition to "set up the request" / "process the response" steps, so step 7/8 of "fetch a single module script" becomes something like

> If custom fetch steps are provided, run them, given _request_. Return from this algorithm and when the custom fetch steps complete with response _response_, run the remaining steps. Otherwise, fetch _request_, and run the remaining steps as part of the fetch's process response for the response _response_.

Then you could maintain a request URL -> response cache on the Worklet object.

I'm open to alternatives though. Maybe if you describe your original plan involving splitting the algorithm in more detail, it would be better?

**Comment by bfgeek** [comment]
Right, the original thought was to effectively split the algorithm into:

(1) "fetch a module script tree resources"

Takes the "url" to produce a tree of "url" - "script source text", this would need to explain that a JS engine could pre-process some source text to resolve and fetch all the required modules, without actually creating a script and binding it to a realm.

This would be sort of steps 1-10 in "fetch a single module script" + fetching the tree.

(2) Upon initializing a WorkletGlobalScope post this tree of "url" - "script source text" over.

(3) "create a module script tree"

Takes the script source tree and just realizes into actual scripts for the global.

But this is pretty nasty :-)

I like just having a cache on the `Worklet` object that fetch runs through, I think they achieve the same thing (I can't think of any side-effects that would be visible from spec'cing one way or another).

As a side note, I've been stalking adamk's module work in v8 and it looks like we'll be able to create an "UnboundModule" in v8 which means we can analyze what we need to fetch early on potentially, and be able to do something similar to the first option internally. I'll sync up with him when i'm in SFO next.

**Comment by domenic** [comment]
Awesome. I'll work on adding the customizable-fetch hook to HTML, probably early next week, but in the meantime you can proceed to assume it'll look pretty similar to the above.

**Comment by bfgeek** [comment]
Sounds great!

**Comment by bfgeek** [comment]
This was fixed with 04803c8755444a35ae1174a40abecdac1322f014 which uses a shared url->response object map that all of the worklet global scopes share.
