### ISSUE TITLE
[css-typed-om]: CSSLengthValue cannot represent 0

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#242]
If that is supposed to be a CSSNumberValue there's a problem with properties only accepting lengths...

@bzbarsky

**Comment by tabatkins** [comment]
"0" is a length in some circumstances, just written without a unit.  The fact that it parses as a number-token rather than a dimension-token is irrelevant, as this is just a syntax convenience.  You represent a zero length in JS by actually using a length type.

(I suppose we do need to specify which unit `width: 0;` is - the obvious answer is `px`.)

**Comment by annevk** [comment]
Yeah, ideally the parser would define that... That does seem to be what implementations do based on a quick test.

**Comment by bzbarsky** [comment]
If we don't expect to roundtrip 0 in cssText and CSSOM reflection, then CSSLengthValue not representing it is probably OK.  But that needs to be a conscious decision.  This is obviously only relevant to CSSOM for specified values.

**Comment by tabatkins** [comment]
Conclusion: define that bare `0` canonicalize to a 0px length.
