### ISSUE TITLE
[css-typed-om]: number and length representations might be wrong

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#243]
Per @bzbarsky: "The way number and length values are set up assumes range restrictions are always at compute time, whereas currently a bunch of properties have them at parse time (e.g., enforcing non-negativeness). This is a pretty major change and it's not clear to me why it's desirable."

**Comment by tabatkins** [comment]
This is not without precedent - wrap a number/length in a calc() and suddenly it becomes clamped rather than invalid.  Similar here - doing JS stuff (at many stages in the value pipeline, depending on exactly which API you're discussing) gets fragile if things can start throwing or rejecting; clamping is friendlier.

**Comment by shans** [comment]
Animations (particularly additive animations) are another example of where late clamping is desirable. It's not possible to represent negative additive offsets of some values in the current OM; the typed OM hopes to fix that.

**Comment by shans** [comment]
We have discussed this in face-to-face meetings and the group agreed that range restriction at computation time is desirable.
