### ISSUE TITLE
[css-typed-om] Stringification behavior

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#268]
What is the StylePropertyMapReadOnly supposed to stringify to? It's not clear from the spec.

**Comment by shans** [comment]
Tab will write prose detailing stringification of StylePropertyMapReadOnly.
Shane will write a section describing how CSSStyleValues are serialized.

**Comment by shans** [comment]
There's an issue for discussion here: what representation should we serialize?

Typed OM tries to provide a minimal representation for values - e.g. for positions, 'center' and '50%' are represented as identical values. This is the first option for serialization (minimal representation).

The old CSSOM has an arcane collection of rules around what's squashed and what isn't. 'center' is kept distinct from '50%' in specified style because keywords are represented differently to lengths. Trying to be faithful to these rules is the second option (existing representation).

A third option is to always use the source string when available (faithful representation).

What I've currently specced is a combination of these three representations, but we should work out exactly what behavior we want in what circumstance.

**Comment by shans** [comment]
Resolved on the minimal representation for computed style: https://log.csswg.org/irc.w3.org/houdini/2016-09-22/#e727340.

It looks like we settled on the same for specified style too but there's no explicit resolution.

**Comment by darrnshn** [comment]
Did we resolve what `StylePropertyMapReadOnly` serializes to?

**Comment by darrnshn** [comment]
Do we actually need a stringifier? AFAIK `element.style` doesn't have a stringifier either.

**Comment by tabatkins** [comment]
Correct, it doesn't, at least in Chrome - `document.body.style + ""` just returns `"[object CSSStyleDeclaration]"`, the default object stringification behavior.

So let's punt this indefinitely until someone figures out a need for it?

**Comment by bzbarsky** [comment]
@tabatkins Shouldn't you remove the stringifier from the IDL then?

**Comment by darrnshn** [comment]
Oops, we must've forgot ^.^ I'll take this.
