### ISSUE TITLE
[css-paint-api] Decide what to do about cursor.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#33]
The CSS property cursor accepts an `<image>`. Is there implementation complexity if we allow cursor to be invalidated every frame? Should cursor just have the opportunity just to paint once?

**Comment by frivoal** [comment]
If we want to parallel the approach taken for SVG in the cursor, we could say:
- The UA **must support** custom painted **non animated** cursors (i.e. a single paint callback)
- The UA **should support** custom painted **animated** cursors (i.e. multiple paint callbacks)

Otherwise, if we chose to skip support for custom paint in cursors, I still think we should extend the &lt;image> type and blacklist the cursor, rather than create a superset &lt;image-or-paint> type and have whitelist everything that should accept it. It seems much more maintainable.

**Comment by tabatkins** [comment]
If you can only paint once, there's really no benefit over just providing a static image.

The problem with painting cursors is that we have to render to an intermediate pixel buffer, to pass to the OS.  That implies dropping to the software rendering path.  This is apparently problematic, according to Elliot.

**Comment by frivoal** [comment]
> If you can only paint once, there's really no benefit over just providing a static image.

Limited benefits, but not no benefit.
* lower file size for things easily generated
* the size of the paintable area is only exposed through the geometry object you get in the paint callback, so if you want to tailor the image to it, you can't do it by just loading an image.

example: I want to the cursor to be a Mandelbrot with as much detail as the cursor will hold. Doing that with image-set(), anticipating many possible cursor sizes and screen density would be terribly inefficient compared to generating it programaticaly for the exact geometry you end up having.

A mandelbrot is not a useful cursor in any situation I can think of, so this isn't meant as a use-case, merely as a demonstration that even with a single callback custom painted cursors can do things you cannot do well otherwise.

Now, whether this difference in capabilities actually addresses any meaningful use-case...

**Comment by tabatkins** [comment]
File size is *generally* a concern, but for things the size of cursors, irrelevant.

Similarly, at the tiny size cursors are displayed at, detail is only barely relevant.  Authoring a few image-set() variants is trivial, because you don't have much space to work with anyway.

**Comment by RByers** [comment]
IIRC we don't support (and AFAIK have no plans to support) animated cursors (SVG or otherwise) in blink for this reason.  Every time the cursor changes to a new custom image we have to send an IPC to the browser process (with a bitmap of the image) and call an OS API to update the cursor.  I believe IE is the only browser that does, and even then they probably hand off the entire animation (as a sequence of frames in an ani or gif file) to the OS. 

I'd say for now we should just disallow `paint()` with `cursor`.  Or if that would be weird, define it such that it gets painted exactly once.  Although there might be a problem with the cursor not having an intrinsic size (it takes the size of the image provided).

**Comment by bfgeek** [comment]
It was resolved that we should disallow `paint()` with `cursor` at the F2F, this was fixed with e842bbcb384821a15d31d0a66492c227d7c21a4e .
