### ISSUE TITLE
Nested CSS Selectors will be implemented?

### ISSUE THREAD

**Issue by adamos42** [w3c/css-houdini-drafts#333]
I know the CSS selectors nesting is not the way how the CSS does, but in multiple CSS extension you are able to do it and programmers love it. I want to know that it will be in the platform in the future?

Current CSS:
```
body {
    margin: 0; padding: 0;
}
body > main {
    width: 900px; margin: 0 auto;
}
body > main > h1 {
    color: HoneyDew;
}
body > main > p {
    color: #222; margin: 0; padding: 0 0 8px 0;
}
```

Expected CSS:
```
body {
    margin: 0; padding: 0;
    main {
        width: 900px; margin: 0 auto;
        h1 {
            color: HoneyDew;
        }
        p {
            color: #222; margin: 0; padding: 0 0 8px 0;
        }
    }
}
```

**Comment by tabatkins** [comment]
[As it turns out](https://tabatkins.github.io/specs/css-nesting/), "naked" nesting like that has grammar problems, which Sass and other langs are okay with swallowing, but the browsers aren't.  (Specifically, you can't tell apart arbitrary selectors and properties in a finite number of tokens; theoretically you have to read forward forever until you run into something disambiguating the two.)

In general, Houdini isn't about adding new features to CSS, but rather making CSS extensible, so that authors can add the features themselves (and show us what needs to be added to the core language). There are some Houdini features that might help in this regard; in particular, custom at-rules (letting people define a `@--nest` rule) would work.
