### ISSUE TITLE
[worklets] (bikeshedding time!) import() name is potentially confusing...

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#374]
So the [import](https://drafts.css-houdini.org/worklets/#dom-worklet-import) function has been noted as potentially confusing.

Other names which have been discussed at some point are:
`loadModule` (@adamk)
`distributeScript` (@annevk)

For additional context the other way to invoke scripts will be via the script tag most likely, e.g.
```html
<script worklet="paint" src="paint.js"></script>
```

Which is the same as
```js
CSS.paintWorklet.import('paint.js');
```

From https://github.com/w3c/css-houdini-drafts/issues/373 originally.

**Comment by annevk** [comment]
Is there a dedicated issue for the `script` element extension? That will need some bikeshedding as well. In particular, it probably needs to use the `type` attribute to avoid running the script in older browsers.

**Comment by bfgeek** [comment]
Filed: https://github.com/w3c/css-houdini-drafts/issues/376 for designing that.

**Comment by bfgeek** [comment]
cc/ @nyaxt, @nhiroki for naming suggestions :)

**Comment by nhiroki** [comment]
Yeah, ```Worklet.import()``` and module’s ```import``` statement are so confusing when we discuss the design of implementation.

I feel ```Worklet.distributeScript()``` (or ```Worklet.distributeModule()```) would be more descriptive of its behavior.

Other idea: ```Worklet.spawn()```?

**Comment by annevk** [comment]
I like spawn, short and sweet.

cc @domenic

**Comment by domenic** [comment]
I don't have strong opinions. import() isn't that bad IMO. spawn() seems nice if it fits with the model. importInto() is another idea.

**Comment by bfgeek** [comment]
cc @surma halp.

**Comment by nyaxt** [comment]
I'm ok with `import()` or `spawn()`

**Comment by nhiroki** [comment]
Just in case, my previous comment is from implementer's pov. Probably web developers have different impressions, and I'm also ok with import() if they aren't confused by it :)

**Comment by surma** [comment]
(Before I start: I could settle for `spawn()`, but I don’t think `import()` is confusing – on the contrary, it’s functionality is pretty similar, warranting a similar name.)

Okay, here goes: This has been buggy me for a while but I never said anything because I thought this was a done deal, but I guess now is my chance 😅 

I always found it weird that theres some sort of magic global for each worklet that loads code. That code than proceeds to create an instance of something that – from there on in – would usually be referred to as “my XYZ Worklet”.

Taking some inspiration from workers, I’d find something like `new CSS.PaintWorklet('myfile.js')` much more intuitive. You‘d have a proper reference to hold on to for message passing and deregistering etc. Wondering what others think, if that’s semantically coherent and whether I just lost all credibility.

**Comment by surma** [comment]
> it probably needs to use the `type` attribute 

What would a MIME type look like, here? `application/javascript+XYZWorklet`?

**Comment by jakearchibald** [comment]
Module scripts don't use a mime type, so this probably shouldn't. I think that discussion is happening in #376.

**Comment by jakearchibald** [comment]
A constructor like @surma suggests makes sense if having an instance is useful.

In terms of a method, does it need to be more complicated than:

```js
await CSS.paintWorklet.add('paint.js');
```

**Comment by annevk** [comment]
I think the reason there's no constructor is because it doesn't make sense to have more than one instance, so you'd need to keep global state to prevent multiple instances at which point you might as well just have it there. And the main reason to favor something like `spawn` over `import` is because the code can end up running in multiple globals (or is guaranteed to, in case of paint worklets).

**Comment by bfgeek** [comment]
@nhiroki FYI :)

**Comment by nhiroki** [comment]
Chromium bug: https://crbug.com/713018

@bfgeek :)

**Comment by hoch** [comment]
Oops. I really need to find a way to get notified this sort of change.
