### ISSUE TITLE
[css-properties-values-api] inherits should be true by default

### ISSUE THREAD

**Issue by LeaVerou** [w3c/css-houdini-drafts#434]
Spec section: https://www.w3.org/TR/css-properties-values-api-1/#registering-custom-properties

I just had a rather confusing experience using `CSS.registerProperty()` to make a property animatable. For reference, my code was:

```js
CSS.registerProperty({
	name: "--x",
	syntax: "<number>",
	initialValue: "0"
});
```

My CSS thus far had been designed with the assumption that the property inherits, which is the default behavior of custom properties. Once `CSS.registerProperty()` was used, suddenly various parts of my CSS code stopped working. At first I thought I was dealing with an implementation bug! Eventually I realized that `inherits` is false by default, so my property had stopped inheriting even though I hadn't declared anything about inheritance.

Given that any unregistered properties inherit by default, it doesn't make sense to have a different default for registered properties. I suspect many future authors will face the same confusion as I just did. The defaults of `CSS.registerProperty()` should be those that cause no changes for things that have not been explicitly specified, whenever possible.

**Comment by thebabydino** [comment]
I was confused by this as well as I was looking at an example and couldn't understand why `inherits` was set explicitly, since I thought the default was `true` anyway. I was convinced it was redundant and that I could omit it. It took seeing this issue to figure out that it does need to be set. Unless you want it to be false.

**Comment by tabatkins** [comment]
Reason we defaulted it to non-inheriting is because that's the more performant option when you don't need inheritance; inheritance is actually relatively expensive.  The confusion y'all bring up is totally reasonable, tho.

We decided to instead just make the "inherits" key required, so you have to specify whether it does or not, and you get an informative error if you leave it out. That should avoid the confusion over omitting it, without defaulting people to the slower option.

**Comment by LeaVerou** [comment]
Given that most properties will likely not be registered (since the main benefit of registering is animation) how important is the performance gain on a tiny percentage of properties to warrant the usability hit of lacking sensible defaults? (currently the defaults are not sensible; with this resolution there will be no defaults, so in both cases sensible defaults are lacking).

**Comment by FremyCompany** [comment]
One of the reasons is that custom properties are currently not being interpolated, so the inherit-induced updates only needs to happen on initial cascade. Otherwise you need to worry about changing its value every frame during animations and transitions. This means invalidating a lot of styles.

**Comment by tabatkins** [comment]
(Or rather, it only changes once during interpolation. Still much cheaper than updating inherited values every frame.)

**Comment by gagyibenedek** [comment]
+1 for what @LeaVerou  and @thebabydino  are saying. I understand, that it's a performance hit, but on the other hand the use-case most people will use it for is to animate multiple values with the same variable (if there's only one no custom prop is needed), and in this case they have to set it to true anyway. 
Making it required seems like a good compromise.
