### ISSUE TITLE
Add CSSMathValue Serialization body

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#489]
CSSMathValue objects are serialized into a calc() expression - add text pertaining to that

**Comment by darrnshn** [comment]
@tabatkins For something like `CSSMathNegate(CSSMathSum(CSS.px(1), CSS.percent(1)))`, did we want to serialize to something like `calc(- calc(1px + 1%))`? But according to the [calc grammar](https://drafts.csswg.org/css-values-3/#calc-syntax), it doesn't look like this is valid. Thoughts?

**Comment by darrnshn** [comment]
Similarly, what do we do with n-ary operators that have only one value: `CSSMathSum(1)` or `CSSMathProduct(1)`?

**Comment by nainar** [comment]
Re: 1 question: Remove the nested calc and the result would be -(1px + 1%)

Re: 2 question: They will serialize into a calc containing that 1 value.

**Comment by darrnshn** [comment]
@tabatkins I went through the new algorithm manually to write some tests, looks good! I think the only 'weird' case is `CSSMathSum(CSSMathNegate(1), 2, 3)` which would give `calc((-1) + 2 + 3)` instead of, say, `calc(-1 + 2 + 3)`. However, I think the former is better as it explicitly reflects the original structure and is more readable.

**Comment by tabatkins** [comment]
Yeah, I think that's fine. If you actually wrote `calc(-1 + 2 + 3)`, it'll normalize to a `CSSMathSum(-1, 2, 3)` and then serialize back to `calc(-1 + 2 + 3)`, so the parens from an explicit `CSSMathNegate` seems fine.  (It's similar to `CSSMathSum(CSSMathSum(1, 2), 3)` serializing to `calc((1 + 2) + 3)`, which is intentional.)

However, if you write `calc(1 - 2 + 3)`, it'll normalize to `CSSMathSum(1, CSSMathNegate(2), 3)`, but it'll serialize back to `calc(1 - 2 + 3)`. Hm.  Possibly this means we should just make the normalization smarter, so that it'll normalize to `CSSMathSum(1, -2, 3)` instead of putting in a `CSSMathNegate` unnecessarily.

**Comment by tabatkins** [comment]
Upon review, nah, everything's fine.  Normalization will *never* produce a Negate or Invert as the first argument of a Sum/Product unless you really do need the parens, like `calc(-(1px) + 2px)`.

Theoreticallly we could actually track the operator used in a sum/product expression, but that's busy work that duplicates the Negate/Invert classes, solely for the purpose of more precisely reproducing the original serialization in some cases. Not worth it.
