### ISSUE TITLE
Add text for computed CSSMathValue objects

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#490]
Add text about how CSSMathValue objects are reduced during computation

**Comment by darrnshn** [comment]
How difficult is this? I'm guessing you'll just take the computed value of the <calc> and normalize that into CSSMathValue?

**Comment by darrnshn** [comment]
Should be simple once text for <calc> computed value is written.

**Comment by tabatkins** [comment]
Closing, since this isn't the responsibility of TypedOM - how computed values are produced from specified values is a CSS thing, TypedOM only concerns itself with how to produce a new TypedOM value from a CSS value (and vice versa).

The CSS V&U spec is hand-wavey about this issue; it describes how to *serialize* a computed math function, which *implies* how a computed value is simplified, but doesn't actually state that.  Needs to be fixed in V&U, so I've opened <https://github.com/w3c/csswg-drafts/issues/2245>.
