### ISSUE TITLE
[css-typed-om] What should CSSStyleValue.parseAll do for non-list-valued properties?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#502]
Following [the algorithm for parsing a style value](https://drafts.css-houdini.org/css-typed-om-1/#parse-a-cssstylevalue), if we called `parseAll` with a non-list-valued property (e.g. `parseAll('color', 'red')`), then we would skip steps 4 and 5 because it's not a list-valued property, and end up returning a `CSSStyleValue` representing `red` in step 6. However, the return type of `parseAll` is an optional `sequence`. I'm guessing the intention is that we return a single-element sequence containing `red`, but I'm not sure if that's clear from the spec.

**Comment by shans** [comment]
My first instinct is that parseAll should always return a sequence for the purposes of future-proofing (otherwise the return value might change if a property were promoted to list-valued in the future).

However, something else  I noticed - append() and set() can't take sequences, they need to take individual values. That makes parseAll more painful to use in some cases, as you need to prepend the property value then .apply the result to append/set.

Maybe we should also modify these methods to take a list of both primitives and sequence args?

**Comment by tabatkins** [comment]
No, don't make them take either. They take rest args; you can just do `styles.set('color', ...myVals)`.

**Comment by tabatkins** [comment]
But yeah, parseAll() should return a list even if the property isn't (currently) list-valued.
