### ISSUE TITLE
[css-typed-om] What to do when CSSNumericValues form a cycle?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#513]
With mutable CSSNumericValues, I think it's possible to form cycles:
```javascript
let a = new CSSMathNegate(0) // a = (- 0)
let b = new CSSMathNegate(a) // b = (- a)
a.value = b // b = (- a) and a = (- b)
```
If this is possible, should `a.value = b` throw an error? Otherwise, type checking will get kinda weird and serialization will be impossible.

**Follow up question**: If we disallow cycles, we can still form a directed acyclic graph. I'm guessing that's allowed, with type checking propagating through the graph when a node changes their `value`? (i.e. a node has to notify its 'parents' when its type changes)

**Comment by tabatkins** [comment]
Heh, don't even need to invoke a second object:

```
let a = new CSSMathNegate(0);
a.value = a; // ?????
```

I think the fix for this is, upon `a.value = b` (or equivalent construction), crawl b's value and see if the a object lives anywhere in it.

I think this still allows, say, `new CSSMathSum(a, a, a, a, a)` to work just fine.

Your follow-up question is more difficult, and means the resolution we made today for CSSUnitValues is kinda useless...

**Comment by tabatkins** [comment]
Actually, if we solve https://github.com/w3c/css-houdini-drafts/issues/494 in the way I want (making `.value`/`.values` readonly), this goes away, as you can't construct cycles in the first place.

**Comment by darrnshn** [comment]
This is pretty much the same as #494. Gonna close this.
