### ISSUE TITLE
[isolated-workers] Code Idempotency

### ISSUE THREAD

**Issue by padenot** [w3c/css-houdini-drafts#54]
I know this is in a non-normative section, but it seems overly restrictive in
scope. Is is an explicit goal for the audio and video applications to keep
state, whether it is input recording, buffering, stateful processing with
accumulation registers, etc.

Setting custom state on `IsolatedWorker` using expandos needs to be a
first-class practice.

**Comment by bfgeek** [comment]
Treat the non-normative sections as "This is where I think the spec will go at the moment, the normative sections will eventually say what they say".

Basically this line:
"The lifetime of an IsolatedWorkerGlobalScope is tied to the execution lifetime of a method or set of methods on a class, not to the lifetime of the IsolatedWorker object."
Is saying that after we run your callback, we might kill you.

For style/layout/paint this is desirable as we don't want different UA behavior depending on how many times per frame we call you function.
UAs for layout/paint today have very different call behavior when it comes to layout-algorithms / paint-walking depending on what optimizations are present in the engine.
E.g. I believe flexbox has optimizations where if you haven't performed them you need to call layout twice on certain children vs. once. With nesting this could be 4x vs. 2x etc.

For rendering in particular we don't want to end up in a situation where if you develop for browser "A" (and add stateful information), you end up with broken behavior for browser "B" in weird edge-cases.

A few questions so I understand this better...

If an AudioGlobalScope dies (because of memory pressure or similar), and if it has an AudioNode with an accumulator or similar; restarting the GlobalScope will result in broken behaviour?  
I.e. it is expected that AudioGlobalScopes won't be killed?

How common is the accumulator use-case for audio?
Can it be done with an additional declarative node as an input to the "ScriptAudioNode"?

For Audio/Video is there a case like above for rendering where different UAs will call different times into a callback? (Probably not, just making sure).

It might be the case that in the spec you can have two types of GlobalScope lifetimes defined, I.e.
"Persistent: The lifetime of an IsolatedWorkerGlobalScope is UA specified."?
"Transient: The lifetime of an IsolatedWorkerGlobalScope is tied to the execution lifetime of a method or set of methods on a class, not to the lifetime of the IsolatedWorker object."

**Comment by padenot** [comment]
> If an AudioGlobalScope dies (because of memory pressure or similar), and if it has an AudioNode 
> with an accumulator or similar; restarting the GlobalScope will result in broken behaviour?

There has not been a decision on the behaviour to adopt yet. A reasonable solution would be to make it a no-op, but that's just my take on it. Also this would happen, most of the time, when CPU usage exceeds the real-time limit (i.e. it takes more than Xms to compute Xms of audio) repeatedly.

 > I.e. it is expected that AudioGlobalScopes won't be killed?

It is expected that script would stop running, but it is also expected that the rest of the graph connected to and from this IsolatedWorker would continue to behave normally.

> How common is the accumulator use-case for audio?
> Can it be done with an additional declarative node as an input to the "ScriptAudioNode"?

Keeping state is a very common case, and is what authors expect. Some things (filters, algorithm, etc.) are going to be implementable with inputs, some things really need to be hooked up in the scope.
Some things can be done in a stateless fashion, but that's only one use-case.

> For Audio/Video is there a case like above for rendering where different UAs will call different 
> times into a callback? (Probably not, just making sure).

I don't think so, the point in time where script would run would be spec-ed without ambiguity:

- For video, on a new decoded/about to be presented frame
- For audio, exactly every 128 sample-frames

**Comment by padenot** [comment]
Any news on this ? I'm going ahead and assuming in my prose that we can set expandos, because `AudioWorklet` is going to be useless without state.

**Comment by bfgeek** [comment]
Yup, the lifetime of the global scope is now:
"The lifetime of a WorkletGlobalScope should be defined by subsequent specifications which inherit from WorkletGlobalScope."

I'll reword this section to include that state should be stored on class instances. And if a subsequent specification says that global scope doesn't die, its safe to assume state on the class. If the subsequent specification doesn't, you can't and should provide an api to store state.

For paint/layout/other things we'll probably provide an API to store permanent state like this.persistentState (which structured clones), but since you aren't killing AudioWorkletGlobalScope everything is good.

**Comment by padenot** [comment]
Very well, this is what (the AudioWG) we need, I'm closing this.
