### ISSUE TITLE
[css-typed-om] should the percent hint concept allow percentages to be numbers?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#580]
The [section on numeric value typing](https://drafts.css-houdini.org/css-typed-om-1/#numeric-typing) defines a concept called a percent hint that seems to suggest what type a percent is compatible with.  However, a bunch of the mechanisms here (such as the way the percent hint is stored, I think, and also the rules for adding types) don't seem compatible with the idea that a percent can be equivalent to a number, as it is for the CSS [`opacity`](https://drafts.csswg.org/css-color-4/#transparency).

I haven't entirely gotten through to see how percent hints end up being used (and some pieces still don't look fully fleshed out, e.g., the definition of `type()` on [`CSSNumericValue` itself](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue)), but it seems like this might be problematic.

**Comment by tabatkins** [comment]
We explicitly discussed 'opacity' in the context of normal CSS `calc()`, and agreed that numbers and %s can't be combined, as it makes unit algebra intractable.  The lack of ability for the percent hint to be "number" is very intentional.

Percent hints just record what unit type a % ended up being resolved to, to make sure that you don't combine an expression that unified %s with lengths and an expression that unified %s with angles (even if the expression types end up being compatible at the point you're using them), because you can only resolve a % to a single type in a particular expression.
