### ISSUE TITLE
[css-typed-om] Does the is2D design allow for inconsistent interpretation of CSSTransformComponents?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#610]
The [section on `CSSTransformValue`](https://drafts.css-houdini.org/css-typed-om-1/#transformvalue-objects) defines an `is2D` attribute on all of the `CSSTransformComponent`s that is defined as:

>  The is2D attribute indicates whether the transform is 2D or 3D. When it’s true, the attributes of the transform that are relevant to 3D transforms (such as the CSSTranslate.z attribute) simply have no effect on the transform they represent. 

I worry that making it work this way might lead to inconsistent interpretation of these components.  That is, if some code looks at the values of a `CSSTranslate` to determine what it means without looking at the `is2D`, it would interpret a nonzero 'z', whereas that's not the way implementations interpret it.  It also means that any code developers write to interpret what a `CSSTranslate` means needs to consider the `is2D` to avoid this.

Avoiding this would presumably require that the getter for `CSSTranslate.z` always returns a zero value.  Then there's the question of how to get to that state:  presumably setting `is2D` to `true` would have to change the state, but would the `z` setter throw, or just drop the value on the floor?  (I'd hope, at least, that setting `is2D` back to `false` wouldn't restore an old value.)  But I'm not sure if this is actually better.

But since I think the current design has potential problems, I wanted to at least get an issue on file; maybe somebody has a better answer.

**Comment by dbaron** [comment]
I'd also note the design:

>  The is2D attribute of a CSSPerspective object must, on setting, do nothing.

**Comment by tabatkins** [comment]
The ["is2D design considerations" section](https://drafts.css-houdini.org/css-typed-om/#dom-csstransformcomponent-is2d) outlines some of the options we thought thru and rejected.

I don't think there's any unambiguously good solution.  I know we considered auto-setting the 3d-related components to 0 or whatever when is2D was true, but I don't recall why we rejected that.  Maybe we thought it would be *more* surprising to set a translate.z attribute and then get a 0 when you read it back?  I don't have a strong opinion on whether we should do that or not, I suppose.

**Comment by tabatkins** [comment]
As resolving this issue might introduce significant changes to the current design of the objects, we should resolve this sooner rather than later.

@atanassov, can we discuss this at the APAC-friendly CSSWG call next week? @ewilligers already requested several Transforms 2 issues, this is pretty related.

**Comment by atanassov** [comment]
@tabatkins, sure, I'll add it for discussion.

**Comment by tabatkins** [comment]
Shoot, I'd like to re-open this. I was just doing the edits and suddenly remembered why I didn't go down this route - CSSMatrixComponent is Problematic.

CSSMatrixComponent is just a TypedOM wrapper around DOMMatrix, which I think is a reasonable design - there's no good reason to invent a new matrix look-alike class. But in DOMMatrix, the is2D flag is readonly - it tells you whether the matrix is currently describing a 2d or 3d operation, rather than *controlling* whether the matrix is 2d or 3d.

If I apply this resolution consistently, then I need to have CSSMatrixComponent.is2D, when true, somehow reflect down and cause the internal DOMMatrix to throw on operations/sets that would make it become 3d.  That's not possible right now, and there's probably not a good reason to add that functionality.

I now remember mulling over this, when I was earlier considering having the is2D design reflect what we've now resolved on, and couldn't figure out any reasonable way to make it work.

I'd rather not have one subclass act substantially differently than the other subclasses in this regard.

**Comment by darrnshn** [comment]
Should this go to the CSSWG again?

**Comment by tabatkins** [comment]
This is definitely not closed.

**Comment by tabatkins** [comment]
Sigh, while writing up the context for <https://github.com/w3c/fxtf-drafts/issues/255>, I remembered the other reason I rejected this approach originally.  The problem of "sub-objects are mutable" applies to more than just DOMMatrix, it affects *all* of the 3d-relevant attributes.  It's all well and good if I automatically replace the contents of `CSSTranslate.z` with a fresh `CSS.px(0)` object when you set `is2D` to `true`, but right now nothing stops you from just saying `trans.z.value = 5` and making it look 3d again.

To fix this, I need to either create a parallel `CSSUnitValueReadOnly` class (and, I guess, automatically replace it with a standard `CSSUnitValue` when `is2D` is set back to `false`), or give `CSSUnitValue` an internal readonly flag that causes the object to ignore any attempt to set its value, and toggle that on/off when you switch `is2D`.

Neither approach seems particularly fun to me, and we're still stuck with the fact that to apply the WG's intention, `DOMMatrix` *also* needs to do something like this (but with more complexity).  I'd still like to push back on this and just resolve to go with the original "who cares what's in the 3d-relevant attributes" approach. I settled on it for a reason (which I wish I'd remembered in more detail at the start of this issue). :/

**Comment by dbaron** [comment]
I guess there's another question, which is:  should we have `is2D` at all?

**Comment by tabatkins** [comment]
We need it, or something equivalent to it, to reflect CSS's (somewhat unfortunate) distinction between "2d transforms" and "3d transforms that happen to be planar".

Another equivalent design, which I didn't like and rejected early, was capturing the distinction in separate classes entirely - `CSSTranslate2D` vs `CSSTranslate3D` class split.  There are two major problems with this: 1, either `CSSTranslate2D` doesn't have a `.z` attribute at all (in which case code trying to do even fairly trivial things with transforms always has to distinguish between the two types of translates/etc, or else get `undefined`/errors percolating thru their code), or it does, and it's permanently set to `0px`/etc, and we have the same need for a `CSSUnitValueReadOnly` variant (but at least it doesn't need to be switchable back to being readwrite); 2, `CSSMatrixComponent2D` still doesn't work, for the exact reason already outlined in this thread.

One thing we definitely *can't* do, I think, is remove is2D and just *infer* the 2d-ness from the attributes. `transform: translateZ(0)` is used today specifically because it's a no-op 3d transform that triggers the 3d-transform side-effects, and we need to be able to reflect that accurately in the TypedOM.
