### ISSUE TITLE
[css-typed-om] specify CSSMatrixComponentOptions default with IDL defaults?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#612]
The [`CSSMatrixComponent` constructor spec](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssmatrixcomponent-cssmatrixcomponent) says:

> If options was passed and has a CSSMatrixComponentOptions field, set this’s is2D internal slot to the value of that field.

One problem with this is that CSSMatrixComponentOptions probably meant to say is2D.

However, it seems like the normal way to specify these things is using WebIDL dictionary defaults.  Maybe that's better, and it could avoid needing to write the part of this sentence with the mistake?

**Comment by tabatkins** [comment]
Closing the loop since <https://github.com/w3c/css-houdini-drafts/pull/692> reverts #613 and ends up closing this issue as invalid...

No, the lack of a default is intentional.  Specifying one way or the other is an active choice with consequences; our current lack of default lets us at least infer what you might want from the passed matrix.  The only other reasonable option would be to make it *required*, but that doesn't seem necessary.
