### ISSUE TITLE
Gather and publish CSS Typed OM performance data in an explainer?

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#634]
Originally raised by @slightlyoff  here: https://github.com/w3ctag/design-reviews/issues/223#issuecomment-362598754

**Comment by darrnshn** [comment]
I've done some initial benchmarking. **tl;dr** Allocating Typed OM objects is slow, so you have to reuse objects for performance gains.

The [first benchmark](http://jsfiddle.net/tbgj5ybu/) just calls `StylePropertyMap.set` with a precomputed Typed OM object. This shows that skipping CSS parsing indeed brings performance gains [1], as long as we reuse objects. In the benchmark, you can play around with `iterations` to change the amount of reuse per cycle.

The [second benchmark](http://jsfiddle.net/pa7nfg3a/) tests a common use case: getting a value from the style map, modifying it, and then putting it back. Here, strings is slightly faster. I suspect this is because we create a new object every time we call `StylePropertyMap.get`. Perhaps we can optimise for this case with [StylePropertyMap.update](https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-update) (reuse the same object over multiple calls?). Also, the benchmark shows a simple case of parsing a length. If we had to parse complicated objects like transforms in JavaScript (I don't actually know to do this properly), I suspect Typed OM would be faster.

[1] On my Chrome Canary (66) build, I get:
```
string x 18,769 ops/sec ±1.21% (94 runs sampled)
typed x 21,627 ops/sec ±1.86% (88 runs sampled)
Fastest is typed
```

[2] I got:
```
string x 513,838 ops/sec ±1.11% (95 runs sampled)
typed x 480,403 ops/sec ±5.46% (79 runs sampled)
Fastest is string,typed
```

**Comment by darrnshn** [comment]
Hey @dbaron , I was wondering if you know what sort of performance gains the initial Firefox implementation of Typed OM got?

**Comment by foolip** [comment]
> I suspect this is because we create a new object every time we call `StylePropertyMap.get`. Perhaps we can optimise for this case with `StylePropertyMap.update` (reuse the same object over multiple calls?)

I don't have any hands-on experience with the API to say if that makes for a good API or not, but hasten to point out that this would be observable, and so defined by the spec if it isn't already. It's a bit like `[SameObject]` in Web IDL, and it's pretty easy to find inconsistencies between implementations in that arena. With a single shared test we can probably avoid having such a situation for CSS Typed OM, if one doesn't already exist.

**Comment by emilio** [comment]
> Hey @dbaron , I was wondering if you know what sort of performance gains the initial Firefox implementation of Typed OM got?

I don't think anybody had an initial impl on Firefox (only typed custom props were implemented, typed om is https://bugzilla.mozilla.org/show_bug.cgi?id=1278697 which doesn't have any patch or similar).

In any case probably @jyc knows better than I :)

**Comment by tabatkins** [comment]
> I've done some initial benchmarking. tl;dr Allocating Typed OM objects is slow, so you have to reuse objects for performance gains.

This is expected, yeah.  The fast case is indeed something like "build a CSSTransformValue, use it in multiple `.set()` calls across `rAF()` callbacks".

This is why I *really really really* want ECMAScript to give us Value Objects, or Typed Objects as the proposal seems to have evolved into, where they're just wrappers around a chunk of TypedArray data.  These should be much faster because they're immutable and we can reuse them more widely.

(This is also why TypedOM was originally as strongly immutable as we could make it with normal JS objects, so we could replace it with Typed Objects later with minimal breakage. We gave up on this when JS appeared to not be willing to give us the thing in a reasonable timescale; we might have to re-evaluate that.)

**Comment by darrnshn** [comment]
After some improvements to performance of StylePropertyMap.get, the [results for the roundtripping benchmark](http://jsfiddle.net/pa7nfg3a/) that I'm getting are:

```
string x 464,227 ops/sec ±2.34% (84 runs sampled)
typed x 519,038 ops/sec ±4.73% (78 runs sampled)
Fastest is typed
```

**Comment by darrnshn** [comment]
Also, Blink uses a character-level "fast path" parser for common CSS values like lengths, but not for more complicated ones. So there are many cases where we can't use the fast path, and Typed OM would be significantly faster (you can try it by putting a space after "px" to not go through the fast path).

**Comment by nainar** [comment]
This issue (even closed) will capture the discussion so closing it as part of issue triaging.

**Comment by tabatkins** [comment]
In particular, my numbers on the "fast path" show an ~30% increase in ops/sec for TypedOM, agreeing with yours, and on the slow path it's nearly 100%:

```
string x 137,575 ops/sec ±5.04% (75 runs sampled)
typed x 225,774 ops/sec ±6.68% (75 runs sampled)
Fastest is typed
```

**Comment by trusktr** [comment]
> These should be much faster because they're immutable and we can reuse them more widely.

Why immutable objects? Immutable patterns are widely know to be slower than mutable patterns. What am I missing here?

**Comment by tabatkins** [comment]
It's entirely dependent on what you're doing with them. Immutable objects allow *sharing*, so you have lower memory pressure and less computation involved in construction. In return, when you do mutate a structure you have to reconstruct parts of it, which can be slower than just doing an in-place mutation. Which of these factors wins in any given scenario depends on your workload.
