### ISSUE TITLE
[css-typed-om-1]Manual definition of the map entries for StylePropertyMapReadOnly contradicts Web IDL

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#652]
https://drafts.css-houdini.org/css-typed-om-1/#stylepropertymapreadonly-map-entries defines what the "map entries" are for a StylePropertyMapReadOnly.

But that's already defined by <https://heycam.github.io/webidl/#es-maplike>:

> This Map object’s [[MapData]] internal slot is the object’s map entries.

(Should be [[BackingMap]]; filed https://github.com/heycam/webidl/issues/521 on that.)

That is, "map entries" is a concept in the language-independent part of Web IDL, but in the ES binding it's defined to be a very specific thing.  You can't override that definition here, not least because all the maplike functions manipulate the [[BackingMap]].

**Comment by bzbarsky** [comment]
Note that this may affect all the places where the "map entries" are used in algorithms in this specification.  At the very least, the uses of "map entries" here are assuming a mapping from the nowhere-defined shorthand this specification uses to actual operations on ES Map objects.  These need to be clearly defined to avoid issues like https://github.com/heycam/webidl/issues/254

**Comment by bzbarsky** [comment]
As a simple example, because there is no infra ordered map involved, and because ES maps only store ES values, the actual values stored are ES Arrays.  Presumably created in the global of the StylePropertyMap.

So when https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-append step 8 wants to append to the array, that needs to be defined very carefully, because this is a page-observable operation that can trigger side-effects in various different ways depending on how it's defined.

**Comment by tabatkins** [comment]
Ooooh, this seems like an unfortunate IDL bug. There's no reason to expose all the terribleness of page-observable ES objects to specs wanting to manipulate their internal data structures.

I had assumed that the "map entries" worked the same as the "indexed properties", which are definitely a spec-defined list.  Reading over this in more detail, it seems a bit clumsy - the maplike has a Map in an internal slot, but the Map's [[MapData]] is just the "map entries" thing defined earlier. This means that the "map entries" should be an **spec-ES List**, not a real-ES Array or anything.  Hopefully we'd be able to work on Infra types here and have a natural mapping to the ES-internal concepts.

Really it looks like this should instead be working with spec types (either Infra or ES) the whole way thru, rather than cramming a real-ES object in the middle of the algorithms?

**Comment by bzbarsky** [comment]
Oh, and I agree that for your use case you really want a thing that just stores Infra bits all over.  But then you have to go define iteration.

**Comment by tabatkins** [comment]
I mean, I'm already violating WebIDL with my maplikes because they're multimaps. If I have to go full-bore "this is internally an Infra list, here's manual redefinitions of all the Map methods", I'll do it.  I'll just be extremely unhappy about it.

But I'll be *less* unhappy than I would be to have to very carefully write correct real-ES handling of an Array that's never even exposed to the user (as I assumed an Array was only generated when the internal data got surfaced in .getAll()).

**Comment by bzbarsky** [comment]
The way maplikes are defined in Web IDL right now the getAll() call returns the already-existing array.  And the next getAll() call returns the same array.  And the caller can mutate it.

And yes, I know that's not the semantics you want.

**Comment by tabatkins** [comment]
Cool cool, it's very good that everything's broken. Sigh.

**Comment by tabatkins** [comment]
No longer using `maplike<>`, and the new design seems to avoid this problem by sticking with Infra types all the way thru (which only get instantiated into concrete ES types when they "leave the system" at `.get()` time).
