### ISSUE TITLE
Need to prefix the Translate, Scale, etc. constructors

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#66]
They're too generic to be left in the global namespace.

Will need to bug @heycam about this.

**Comment by heycam** [comment]
So this would be something like:

```
[Constructor(...)]
interface CSS.Length {
  ...
};
```

and that would place the constructor on [the CSS object](https://drafts.csswg.org/css-conditional-3/#the-css-interface).  You could write `new CSS.Length("4px")` in JS.

I'm curious what @domenic, @annevk, @bzbarsky think.  This would set a precedent, since we don't hang interface objects off anything else at the moment, but I can't see a particular reason why it wouldn't work.

**Comment by heycam** [comment]
And there'd be a number of these.  There are five interfaces inheriting from `StyleValue` in [the spec](https://drafts.css-houdini.org/css-typed-om/#stylevalue-subclasses), and another six for the specific `TransformComponent`s.

**Comment by annevk** [comment]
What is wrong with using a prefix as we do elsewhere?

**Comment by domenic** [comment]
I tend to feel it's too little too late. If this IDL feature had been in place a long time ago, we'd have used it everywhere; most specs would be confined to a single top-level name. But since it's not, we have a long history of prefixed constructors. We should probably be consistent with those, until the greater opportunity comes along to just stuff everything in a built-in module.

In other words, I don't see value in: a lot of prefixed constructors from the past; a few namespaced constructors created during the current era; then in the future a lot of constructors placed into a built-in module. We should just narrow that down to a lot of prefixed constructors from the past, plus a lot of constructors placed in a built-in module for the future.

**Comment by esprehn** [comment]
Yeah, I'd rather we used prefixes for this.

**Comment by shans** [comment]
Prefixes added in https://github.com/w3c/css-houdini-drafts/commit/f5a721a0487dacf7e08cd54df98f6be07cd4fd35

**Comment by annevk** [comment]
Thank you.
