### ISSUE TITLE
[css-properties-values-api] Syntax-checking in CSSStyleDeclaration.setProperty

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#778]
In the current implementation of css-properties-values-api/cssom in Blink, it is not allowed to set a registered custom property to an invalid value using setProperty. The value is just discarded.

**Should setProperty still discard invalid values for registered custom properties?**

Example:

```
<!DOCTYPE html>
<script>
    CSS.registerProperty({
        name: '--color',
        syntax: '<color>',
        initialValue: 'green',
        inherits: false
    });
</script>
<style>div { --color: red; }</style>
<div id=target></div>
<script>
    // Has no effect:
    target.style.setProperty('--color', 'url("not-a-url")');

    // Actual: red
    // Expected (by andruud): green
    console.log(getComputedStyle(target).getPropertyValue('--color'));
</script>
```

This was allegedly [1] the agreed-upon behavior at some point, but as of https://github.com/w3c/css-houdini-drafts/commit/8dfc2d985618a23f97e05c42f7ef6b083ef3256d , this behavior seems inconsistent. I think it's more in line with the new spec wording to let setProperty ignore whether the property is registered or not, and do syntax-checking computed-value time.

[1] https://codereview.chromium.org/2607403002

**Comment by andruud** [comment]
The same goes for Typed OM, registering a property should have no effect on declared/inline style, but for computedStyleMap, getters return typed values after registering.

**Comment by andruud** [comment]
.. or maybe not.

I guess it's kind of weird if, for a `<length>`-registered property `--foo`, this was invalid:

```
element.attributeStyleMap.set('--foo', CSS.px(20));
```

**Comment by tabatkins** [comment]
The behavior is inconsistent, but intentional.

Registered custom properties don't reject invalid values at parse time *from a style sheet*, so that browsers don't have to reparse all the styles on the page to determine the correct cascade (or, equivalently, preserve the entire list of cascaded values for every custom property); instead, you just decide at computed-value time whether the value that won the cascade is valid or not.

But there's no similar implementation difficulty for checking the validity of a style set from JS.  Throwing an error gives useful feedback to the author, even if it does mean that there's now an order-dependence in the results.

(That is, setting a property then registering it gives no error, even if the value doesn't match the grammar; it just ends up as invalid at computed-value time. But registering the property and then setting it will throw an error if it doesn't match the grammar.)

I'll amend the note to make it clearer that this is an intentional inconsistency, however.

**Comment by andruud** [comment]
Gotcha. Thanks for that explanation.

The only thing I don't like about this, is that if a value is set with typed OM:

```
element.attributeStyleMap.set('--foo', CSS.px(20));
```

And we reference that value somewhere:

```
width: var(--foo);
```

Then we need to create a "synthetic" token stream for `--foo` for substitution purposes.

But I guess this is no worse than substituting an interpolated value. :slightly_smiling_face:
