### ISSUE TITLE
[css-paint-api] broken links

### ISSUE THREAD

**Issue by svgeesus** [w3c/css-houdini-drafts#787]
I had to fix the following broken links to publish the CR document on w3.org. 

I planned to also fix them in the source but they are not found in the .bs file so it must relate to the automatic bikeshed references stuff.

https://html.spec.whatwg.org/multipage/scripting.html#set-bitmap-dimensions
to
https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-set-bitmap-dimensions

https://html.spec.whatwg.org/multipage/scripting.html#output-bitmap
to
https://html.spec.whatwg.org/multipage/canvas.html#output-bitmap

https://html.spec.whatwg.org/multipage/scripting.html#reset-the-rendering-context-to-its-default-state
to
https://html.spec.whatwg.org/multipage/canvas.html#reset-the-rendering-context-to-its-default-state

https://html.spec.whatwg.org/multipage/scripting.html#concept-canvas-alpha
to
https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-alpha

https://heycam.github.io/webidl/#common-function
to
https://heycam.github.io/webidl/#Function

https://heycam.github.io/webidl/#idl-domexception
to
https://heycam.github.io/webidl/#idl-DOMException

**Comment by tabatkins** [comment]
Nope, every one of them is caused by the spec having a <pre class=anchors>
block manually specifying those particular anchors (and doing so
incorrectly, thus the broken links).  Removing that block, it looks like
all of those terms aren't exported, and currently Bikeshed's error message
for this sort of linking failure doesn't list what to add to your <pre
class=link-defaults> block to resolve them, so this is at least somewhat my
fault.

I'll fix up the spec, and I've opened <
https://github.com/tabatkins/bikeshed/issues/1332> to remind myself to make
this error more informative.
