### ISSUE TITLE
[css-properties-values-api] Consume a component name presumably shouldn't allow CSS wide keywords, but it does.

### ISSUE THREAD

**Issue by emilio** [w3c/css-houdini-drafts#879]
https://drafts.css-houdini.org/css-properties-values-api-1/#consume-syntax-component:

When you hit a `name-start code point`:

> If the stream starts with an identifier, reconsume the current input code point from stream then consume a name from stream, and set component’s name to the returned `<ident-token>`’s value. Otherwise return failure.

Per https://github.com/w3c/css-houdini-drafts/issues/259, I assume that it should match `<custom-ident>`. Blink does throw for this:

```js
CSS.registerProperty({ name: "--bar", syntax: "inherit", inherits: false, })
```

cc @andruud @tabatkins

**Comment by emilio** [comment]
Relatedly, are there WPT tests for this?

**Comment by andruud** [comment]
In my defense, my original PR handled this [[1]](https://github.com/w3c/css-houdini-drafts/pull/860/commits/641be53f3edc14fd1dd48537173e29c9eb81ce3a#diff-a9241a7d4da1a961238474fb2b99cdf1R629), but it got lost in Tab's pass over the text. (Thankfully section 3.1 still says "Any sequence which starts an identifier, can be consumed as a name, and matches the &lt;custom-ident> production", so at least there's that. We should still fix "Consume a syntax component", of course).

I don't remember right now if there's a test for this particular case. I *think* so, as I remember us having `expectations.txt` for something like this due to missing _revert_ support. I'll check tomorrow and add one if it's missing.

Related PR : #861

**Comment by andruud** [comment]
@emilio Yes, [it's covered](https://github.com/web-platform-tests/wpt/blob/master/css/css-properties-values-api/register-property-syntax-parsing.html#L137) by WPT. (Not `revert`, though. I was thinking of [another test](https://github.com/web-platform-tests/wpt/blob/master/css/css-properties-values-api/register-property-syntax-parsing.html#L148)).
