### ISSUE TITLE
Is attributeStyleMap out of date?

### ISSUE THREAD

**Issue by jpmedley** [w3c/css-houdini-drafts#892]
The Typed OM spec currently shows [`attributeStyleMap` on an interface called `ElementCSSInlineStyle`](https://www.w3.org/TR/css-typed-om-1/#declared-stylepropertymap-objects). I can find no such property in Chrome. Yet the Element interfaces shows [a property with this name and a link to the Typed OM spec](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/dom/element.idl?q=Element+f:.idl+file:%5Esrc/third_party/blink/renderer/+package:%5Echromium$&dr=C&l=120)

Should `ElementCSSInlineStyle.attributeStyleMap` (partial) actually be `Element.attributeStyleMap` (partial)?

**Comment by AmeliaBR** [comment]
The `ElementCSSInlineStyle` interface was never directly exposed, it was implemented by element interfaces for element types that have a `style` attribute (HTML and SVG).  The Editor's Draft of the spec [redefines it to use the `mixin` syntax to make this clear](https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-interface).

If Chromium is exposing this on the Element interface, instead of as a mixin on HTMLElement and SVGElement, they are not *quite* to spec, although the functional difference to web authors will be minimal.

BTW, the spec you're linking to, CSSOM, is distinct from the Houdini Typed OM. CSSOM defines the basic ways of accessing style rules and stylesheets as structured objects. [Typed OM](https://drafts.css-houdini.org/css-typed-om/) goes one step further and defines CSS property _values_ (colors, lengths, etc.) as structured objects.

**Comment by tabatkins** [comment]
Amelia is correct.

Note that if you click thru on ElementCSSInlineStyle, you'll find that it has `[NoInterfaceObject]`, which usually means it's intended purely to be used as a mixin, not an interface you actually instantiate. (Now that mixins actually exist in WebIDL, we should convert that over.) If you then search for instances of the term in that spec (or click on the dfn and select some of the links to instances of it), you'll see that it's used in `implements` statements, which is indeed how WebIDL used to do mixins.
