### ISSUE TITLE
[questions] Right or Lie about CSS Houdini?

### ISSUE THREAD

**Issue by ghost** [w3c/css-houdini-drafts#90]
Hello, I have question in category "right or lie"? 

1. It's right that CSS Houdini is not replace described above css3-4 specifications and restrictions. For example, CSS `attr` or `element(#id)`? 
2. It's right that worklets cannot interop with JS, but will have simular API? 
3. Will be raw image data used in CSS, or not? This probably, not related with CSS houdini, probably more to CSS4 Images API. So question - offtop. 
4. It's right that... 

Later will other questions.

**Comment by FremyCompany** [comment]
Hi @acterhd,

Thanks for reaching out, but in the future I think the people working on this repository would all appreciate that you follow some guidelines when interacting here. We want our work at CSS Houdini to be public, but we can't achieve this goal if the noise is so high it becomes impossible to work efficiently. So, when you post here:

1. Please open one thread per issue. You are asking three questions here.
2. Please think about your questions before writing them. Avoid editing your post; it's too late we got the notification email already. 
3. What is the point of asking questions then saying they are off-topic? It makes your reader looses time which is likely to make your next threads going unnoticed because no one here likes to waste time.
4. Please give use cases and examples when you talk about something. I appreciate that you submitted an example on some other thread, and it helped me understand your point way better than those questions; please keep up the great work on that front.

So, to answer your questions specifically, I agree with you that the CSS Paint API which you are currently trying to use does not interact well with native image types. 

- There is no way to depend on an image for your rendering at this point, or do partial rendering as the image downloads. 
- There isn't a way to render an image(...)/element(...) that you get from css values. 

Both of these things are valid issues and should be fixed, indeed.


I don't think we want to allow JavaScript to send data directly to the Custom Paint function, because in the end the features should be defined in CSS, not in JavaScript. You are right that you will need browsers to support "element(...)" before you can render an element via custom painting, this is how CSS works. Modules adds on top of each other, but each module only works on what is required for it to work, not all the bindings. I suggest you push for the "elements" function in the css working group, not in the Houdini group. You can mention your use case, though.


Regarding attr(...), I am not sure what we can do about it since no browser currently support attr(...) for real outside the content property, but I guess we could require browsers supporting the attr(...) function to replace it by its value for Custom Paint and Custom Layout callbacks.

**Comment by myakura** [comment]
the readme says

> Specification issues are raised and discussed in GitHub Issues in this repository.
>
> We also maintain the [public-houdini mailing list](http://lists.w3.org/Archives/Public/public-houdini/) for general-interest topics.

so perhaps you should send them off to the list.

**Comment by acterhd** [comment]
I recently sent issue about `element()`. Very hard issue, because need make `source()` function specification.
