### ISSUE TITLE
[css-typed-om] Update CSSUnitValue not updating element style in Chrome (bug?)

### ISSUE THREAD

**Issue by trusktr** [w3c/css-houdini-drafts#995]
I'm running this in Chrome console:

```js
let Y

document.body.attributeStyleMap.set('transform', 
  new CSSTransformValue([
    new CSSTranslate(
      CSS.px(10),
      Y = CSS.px(100),
      CSS.px(10)
    )
  ])
)
```

This successfully changes the position of the rendered `body`.

However, if I later try to do the following nothing happens:

```js
Y.value = 200 // nothing happens
```

Please tell me this is a bug! :pray: 

It makes so much sense for performance to be able to modify the objects in place without having to create `new` instances. If we have to create `new` instances in an animation loop (for example), **_it will create a needless amounts of garbage to be collected, which is most definitely not ideal._**

**Comment by trusktr** [comment]
Ok, what I found _does_ work, is the following, which is not as intuitive:

```js
let Y

document.body.attributeStyleMap.set('transform', 
  new CSSTransformValue([
    new CSSTranslate(
      CSS.px(10),
      Y = CSS.px(100),
      CSS.px(10)
    )
  ])
)

// ...later...
Y.value += 100
element.attributeStyleMap.set('transform', T) // set it to the same CSSTransformValue value
```

This is great: we don't need to create `new` instances! :partying_face: However, it would be more intuitive and simply if all we had to do was `Y.value += 100`.

Is there a particular reason `Y.value += 100` is designed not to update anything?

Now suppose I have 100 elements, and I want to update styling for all of them using shared CSS OM. This is intuitive:

```js
Y.value += 100
```

while this is less intuitive and more work:

```js
Y.value += 100
for (const el of elements) {
  el.attributeStyleMap.set('transform', T)
}
```

It costs extra operations, and seems like we're not taking advantage of re-usable objects as much as intuition would imply.

**Comment by trusktr** [comment]
Plus, having to iterate over a known set of elements isn't always possible.

For example, what if someone architects a re-usable style system, and allows an end user to apply the style OM to any elements anywhere, arbitrarily.

It may be difficult for the style-system author to get references to all the elements, in order to apply updates, and asking the end user to do so makes it more cumbersome for them.

**Comment by tabatkins** [comment]
This is working as intended. Having "live" values that implicitly update styles when they're changed is a pretty dangerous antipattern, for a few reasons:

* it makes perf much more difficult to manage, introducing more "pause while we restyle the world" cases unexpectedly. (For example, if you're updating both the X and Y coordinates of a CSSTransformValue object, is there any chance the page could restyle *after* you update X but *before* you update Y? Are you *sure*?)
* lifetimes for the objects become *very* tricky - what happens if the style gets updated underneath you? Is the object dead? How can you tell?
* what happens if you .set() one property's object onto another element/property?

Having the objects instead be "dead", so style only updates when you explicitly set them back to the style map, resolves all of these issues very simply.

> It makes so much sense for performance to be able to modify the objects in place without having to create new instances. If we have to create new instances in an animation loop (for example), it will create a needless amounts of garbage to be collected, which is most definitely not ideal.

As you noted in the followup comment, there's no need to `new` up values constantly; it's both allowed and *encouraged* to just reuse the same objects across multiple `.set()` calls, precisely for the perf reasons you mention.

**Comment by trusktr** [comment]
I see what you're saying. So you think (and I agree) it would be bad if modifying any object caused a synchronous style update.

Could the spec be updated so that updating any objects will cause a style update to be queued to happen in the next frame, after `ResizeObserver` tasks?

Seems like this would be a backwards-compatible change.

**Comment by tabatkins** [comment]
Currently the Typed OM relies on the same (generally unspecified) notion of batching style updates that other style-related mutations rely on. When the timing of that batching is properly specified, Typed OM will match all the others.
